# # # # # # # #
#   K i k o   #
# # # # # # # #

# Basic
name:               "thirdj"

# URL
baseurl:            ""
#baseurl:            "" #For Root Domain
#permalink:          /:year/:month/:day/:title.html
permalink:          /:title

# Navigation
nav:
  - name:           "About"
    href:           "/about/"
  - name:           "Twitter"
    href:           "http://twitter.com/thirdjj"
  - name:           "GitHub"
    href:           "https://github.com/thirdj"

# Sass
sass:
  style:            :compressed

# Scopes
defaults:
  -
    scope:
      path:         ""
      type:         "pages"
    values:
      layout:       "page"
  -
    scope:
      path:         ""
      type:         "posts"
    values:
      layout:       "post"

# URL
url:                "http://thirdj.github.io"
